spring:
  application:
    name: 3D-printer-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: flap
    password: 123
    url: jdbc:postgresql://localhost:5433/db-printers
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: 11john2001@gmail.com
    password: naqmlubkgpsmvgta
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:10100}/eureka/

server:
  port: 8080


